In [9]:
!ls /input/uploads/tryp/train/norm

00065bb231c23749f44e37c0193aac47.png  81dff8dfac37cfc6d63e28cc4327c0df.png
000b9c9adf1fc529943ae2fe85e0da18.png  81e312ba617d0c79211e5c6376603887.png
0016712101950a729986859a75559ef0.png  81e4de88f9f2e2b3763a6cada1b6677c.png
002055460f8ab312e78084893ce2d76a.png  81edf9e86b41b82272e37c6364bc7b71.png
0031cd1291297d4bd7b0bed3f4e35b06.png  81f125c04ef87df61b5371affb793e0a.png
00352e1bd99380d5812729c1da625861.png  81f9cacbb2c37c000eaff96eacf58ba4.png
0036cc78c505bc85f749281bb5cfd740.png  81fae254252392c60b87fa913edddc3e.png
003f3bec60cfed62564b7ce1d6567838.png  81fc423507ab8edd77de2bdf0b6c686f.png
00473b444f53ab0ec5b8666deaf52a6b.png  81fed11883c759b5e47192198acb65a9.png
004cf758be7a003f9d8833c055dbbd6b.png  8205224647673d8271a8e011c4db41c9.png
004d252ae70cb298471e97a6597ff3aa.png  8205a92c3fad80cb6d9a496fce65365b.png
0052d55fdd0e644fd1a974028f3a1498.png  820aa7a230f2133ea0bfe0f655ee6b2e.png
005813202cf42318b85a5fce5c6df23e.png  821018a961a505e9bd28c862e2420546.png
005879fc0c156d5398c3d4a7c

54ba5910461cd40887384fa9a0f5e20e.png  d399f94ea4d06c3f18d38e53917f614b.png
54bccb3ee1cf429a8379b6aee363da7b.png  d39bf13aac08a9eab9a5cd514bd3859d.png
54bdb75e80f1d874b9c2a4381d286f6a.png  d39e2b12047e396e2f1b89a288288134.png
54c82fc779d7d2a57bef00a2075d12ee.png  d3a162556661deddfa07347368831a4b.png
54c91c32062e3cdfbff14dbe07f16c36.png  d3a4926d802aba41544fc2bfe7df1ee8.png
54cd8f29b3f33d25881db898e44bbd44.png  d3a9e74992d58550787c3cf0e82c4245.png
54dae0b790b10d4e28e64b416660c5d7.png  d3aa71635d992f5ef088f51d26c387e7.png
54dc22d69ea2522c98aae060b6c1b243.png  d3aa9db695ac73f3894fb54b73b0d73b.png
54e2f0e34c17a94a270b103820e859e8.png  d3b4f3259e9e7da4fc12b35c718b6d22.png
54e62cb18a7db447773969c2ab60877f.png  d3b5b32523dbc20bc41f4ebad94eb056.png
54e70b91d0e4f49f229b87fac0b6353e.png  d3ba015516188dc3ebe221029ffb44c5.png
54eda426d487f7fe9bdd90aa1c56e150.png  d3c4a380a23bfae31ef57e26403bbaa3.png
54f143907cb4d7f9b528056b387a5013.png  d3caae673a65ab610db8680b2fad0ae4.png
54f3282a82b5c8a595f8d25cb

In [51]:
import os
import cv2


dataset_path = '../input/uploads/tryp/'
train_norm = 'train/norm'
train_trypo = 'train/trypo'
valid_norm = 'valid/norm'
valid_trypo = 'valid/trypo'

train_data_ratio = 1.0 # ratio of training data

train_norm_path = os.path.join(dataset_path, train_norm)
train_norm_filelist = os.listdir(train_norm_path)
train_norm_filelist = train_norm_filelist[:int(train_data_ratio * len(train_norm_filelist))]

train_trypo_path = os.path.join(dataset_path, train_trypo)
train_trypo_filelist = os.listdir(train_trypo_path)
train_trypo_filelist = train_trypo_filelist[:int(train_data_ratio * len(train_trypo_filelist))]

valid_norm_path = os.path.join(dataset_path, valid_norm)
valid_norm_filelist = os.listdir(valid_norm_path)

valid_trypo_path = os.path.join(dataset_path, valid_trypo)
valid_trypo_filelist = os.listdir(valid_trypo_path)

def get_images(file_list, path):
    return [cv2.imread(os.path.join(path, image)) for image in file_list]

train_norm_images = get_images(train_norm_filelist, train_norm_path)
train_trypo_images = get_images(train_trypo_filelist, train_trypo_path)
valid_norm_images = get_images(valid_norm_filelist, valid_norm_path)
valid_trypo_images = get_images(valid_trypo_filelist, valid_trypo_path)

print(train_norm_images[0])
print(train_trypo_images[0])
print(valid_norm_images[0])
print(valid_trypo_images[0])

[[[237 237 237]
  [242 242 242]
  [237 237 237]
  ..., 
  [241 241 241]
  [240 240 240]
  [242 242 242]]

 [[231 231 231]
  [235 235 235]
  [238 238 238]
  ..., 
  [240 240 240]
  [242 242 242]
  [245 245 245]]

 [[230 230 230]
  [234 234 234]
  [237 237 237]
  ..., 
  [238 238 238]
  [241 241 241]
  [244 244 244]]

 ..., 
 [[221 221 221]
  [221 221 221]
  [220 220 220]
  ..., 
  [217 217 217]
  [215 215 215]
  [213 213 213]]

 [[221 221 221]
  [222 222 222]
  [219 219 219]
  ..., 
  [216 216 216]
  [216 216 216]
  [215 215 215]]

 [[223 223 223]
  [223 223 223]
  [217 217 217]
  ..., 
  [214 214 214]
  [216 216 216]
  [217 217 217]]]
[[[ 42  35  92]
  [ 32  31 129]
  [ 45  44 158]
  ..., 
  [246 255 252]
  [248 255 252]
  [248 254 253]]

 [[ 43  45 101]
  [ 29  35 120]
  [ 35  41 130]
  ..., 
  [247 253 253]
  [247 253 253]
  [248 255 250]]

 [[ 42  43 108]
  [ 39  47 140]
  [ 41  47 144]
  ..., 
  [250 253 233]
  [251 253 253]
  [246 255 250]]

 ..., 
 [[ 34  39  37]
  [ 14  20  18]


In [52]:
import matplotlib.pyplot as plt

def get_display_image(image):
    plt.figure(figsize=(2, 2))
    plt.imshow(image[:, :, [2, 1, 0]])
    plt.show()

In [64]:
from random import shuffle
import numpy as np
import matplotlib.pyplot as plt
from keras.utils import np_utils

def process_images(images):
    images = np.divide(images, 255)
    return images
    
def permutate_data(norm, trypo):
 #   norm = process_images(np.array(norm))
  #  trypo = process_images(np.array(trypo))
    X = np.concatenate([norm, trypo])
    Y1 = np.zeros(len(norm))
    Y2 = np.ones(len(trypo))
    Y = np.concatenate([Y1, Y2])
    ind = [i for i in range(len(Y))]
    shuffle(ind)
    X_new  = X[ind, :,:,:]
    Y_new = np_utils.to_categorical(Y[ind]) 
    return X_new, Y_new
    
X, Y = permutate_data(train_norm_images, train_trypo_images)
X_val, Y_val = permutate_data(valid_norm_images, valid_trypo_images)
print(Y.shape)

(15884, 2)


In [65]:
import keras
from keras.models import Sequential
from keras.layers import *

#X = X[:700, :, :, :]
#Y = Y[:700, :]

model = Sequential()
model.add(Conv2D(8, (3, 3), padding='same',
          input_shape=(256, 256, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(16, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(8, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(24, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(12, (3, 3), padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(16, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(BatchNormalization())
model.add(GlobalAveragePooling2D())
model.add(Dropout(0.3))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dropout(0.3))
model.add(Dense(2))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [70]:
pred = model.fit(X, Y, epochs=15, batch_size=128)

Epoch 1/1
15884/15884 [==============================] - 61s - loss: 0.3462 - acc: 0.8545    


In [71]:
ev = model.evaluate(X_val, Y_val)
print(ev)

 992/1000 [============================>.] - ETA: 0s[0.37745334196090696, 0.82799999999999996]
